# Generated by Django 6.0.6 on 2026-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=223)),
                ('mobile_number', models.CharField(max_length=12)),
                ('qr_image', models.CharField(max_length=255)),
            ],
        ),
    ]
